DROP DATABASE IF EXISTS storepage;

CREATE DATABASE storepage;

USE storepage;

CREATE TABLE products (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	sku VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL
);

CREATE TABLE books (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	sku VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	price FLOAT NOT NULL,
	weight FLOAT NOT NULL
);

CREATE TABLE dvds (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	sku VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	price FLOAT NOT NULL,
	size FLOAT NOT NULL
);

CREATE TABLE furnitures (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	sku VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	price FLOAT NOT NULL,
	height FLOAT NOT NULL,
	width FLOAT NOT NULL,
	length FLOAT NOT NULL
);